/**
 * js/editor.js
 * Logique Éditeur + Gestion Métadonnées YAML
 */

let input = null;
let preview = null;

// Regex pour détecter l'entête YAML
const YAML_REGEX = /^---\n([\s\S]*?)\n---/;

const configureMarked = () => {
    if (typeof marked === 'undefined') return false;
    if (typeof marked.use === 'function') marked.use({ breaks: true, gfm: true });
    return true;
};

export const Editor = {
    init() {
        input = document.getElementById('markdown-input');
        preview = document.getElementById('markdown-preview');

        if (!input || !preview) return;

        configureMarked();

        input.addEventListener('input', () => {
            this.render(input.value);
        });
    },

    setContent(content) {
        if (!input) return;
        input.value = content || '';
        this.render(input.value);
    },

    getContent() {
        return input ? input.value : '';
    },

    /**
     * Extrait les métadonnées (YAML) pour l'indexation Drive
     */
    getMetadata() {
        const content = input.value;
        const match = content.match(YAML_REGEX);
        let properties = {
            titre_court: '',
            statut: 'actif' // par défaut
        };

        if (match && match[1]) {
            const yamlBlock = match[1];
            
            // Extraction simple ligne par ligne (pas de parser lourd)
            const titleMatch = yamlBlock.match(/titre_court:\s*(.+)/);
            if (titleMatch) properties.titre_court = titleMatch[1].trim();

            const statusMatch = yamlBlock.match(/statut:\s*(.+)/);
            if (statusMatch) properties.statut = statusMatch[1].trim().toLowerCase();
        }

        return properties;
    },

    /**
     * Bascule le statut Obsolète directement dans le texte YAML
     */
    toggleObsolete() {
        let content = input.value;
        let match = content.match(YAML_REGEX);
        
        let newYaml = "";
        
        if (match) {
            // Le bloc existe, on le modifie
            let yamlContent = match[1];
            if (yamlContent.includes("statut: obsolete")) {
                // On repasse en actif
                yamlContent = yamlContent.replace(/statut:\s*obsolete/i, "statut: actif");
            } else if (yamlContent.includes("statut:")) {
                // On passe en obsolete
                yamlContent = yamlContent.replace(/statut:\s*.+/i, "statut: obsolete");
            } else {
                // On ajoute la ligne
                yamlContent += "\nstatut: obsolete";
            }
            newYaml = `---\n${yamlContent.trim()}\n---`;
            content = content.replace(YAML_REGEX, newYaml);
        } else {
            // Le bloc n'existe pas, on le crée
            newYaml = `---\nstatut: obsolete\n---`;
            content = newYaml + "\n\n" + content;
        }

        input.value = content;
        this.render(content);
        return this.getMetadata().statut === 'obsolete';
    },

    render(markdownText) {
        if (!preview) return;
        // On enlève le YAML pour le rendu visuel (c'est moche sinon)
        const contentWithoutYaml = markdownText.replace(YAML_REGEX, '');
        try {
            const html = typeof marked.parse === 'function' ? marked.parse(contentWithoutYaml) : marked(contentWithoutYaml);
            preview.innerHTML = html;
        } catch (e) {
            preview.innerHTML = "Erreur rendu.";
        }
    },

    extractTitle() {
        if (!input) return "FSA_Sans_Titre.md";
        // On cherche le titre Markdown (# Titre)
        const content = input.value.replace(YAML_REGEX, ''); // On ignore le YAML
        const match = content.match(/^#\s+(.+)$/m);
        if (match && match[1]) {
            // Nettoyage pour nom de fichier safe
            return match[1].trim().replace(/[^a-zA-Z0-9àâäéèêëîïôöùûüç_\-\s]/g, '') + ".md";
        }
        return "FSA_Autogenerated.md";
    }
};